project:
  type: website
  output-dir: docs

website:
  title: "RNA-Seq workshop series"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: notebooks/0.0_about.html
        text: "About"
      - href: setup.html
        text: "Setup"
      

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"
          
format:
  html:
    theme: simplex
    css: lesson.css
    toc: true
    code-overflow: wrap
    highlight-style: github




