---
title: "**RNA-seq using Nextflow**"
output:
  html_document:
    toc: false
    toc_float: false

fig-cap-location: top

---

**Synopsis:** This workshop series will introduce you to **RNA sequencing data analysis for differential expression and pathway enrichment**. This is suitable for people who are **new to the command line interface and R**. 

### **Target audience:**
Researchers, students and life scientists who are new to RNA sequencing for differential expression and pathway analysis. The course is beginner friendly and intended for those interested in using the command line interface for their analysis. It is also suitable for those who want to learn about and use [nf-co.re](https://nf-co.re/) workflows.

### **Useful resources**
- Introduction to __[Command Line for Genomics](https://datacarpentry.org/shell-genomics/)__
- __[Nextflow and Supercomputing at Pawsey](https://www.biocommons.org.au/events/nextflow-nimbus)__ : WEBINAR: Portable, reproducible and scalable bioinformatics workflows using Nextflow and Pawsey Nimbus Cloud. 

> * **Own laptop and access to Pawsey Nimbus is required**
{: .prereq}

# Differential expression and pathway analysis 

| Lesson                                                        | Overview                                                                                                                                                                                                     |
|---------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [Set up your computer](https://sydney-informatics-hub.github.io/rna-seq-pt2-quarto/setup.html)| Follow these instructions to install a terminal application and web browser used in the workshop. |
| [Introductory slides](https://unisyd.sharepoint.com/:p:/r/teams/SydneyInformaticsHub2/_layouts/15/Doc.aspx?sourcedoc=%7B02017CE8-31E0-4693-AAA7-27968E003127%7D&file=Sept2022_Introductory_slides_biocommons_template.pptx&action=edit&mobileredirect=true)                                           | Slides that provide the essential theory behind RNA-sequencing experiments for differential expression, and what will be covered in Part 1 & 2 of the RNA sequencing training series            |
| [Part 1. Raw sequence to counts](https://sydney-informatics-hub.github.io/rna-seq-pt1-quarto/)                        | Part 1 of the two-part RNA sequencing workshop series is where participants will understand raw files and use nf.co.re's rnaseq pipeline to transform raw sequencing data into analysis ready count data     |
| [Part 2. Counts to genes and pathways](https://sydney-informatics-hub.github.io/rna-seq-pt2-quarto/) | Part 2 of the two-part RNA sequencing workshop series is where participants will use analysis ready raw count data generated in part 1 of the series to perform differential expression and pathway analysis |
